### ISSUE TITLE
cofgroupmod::set_type

### ISSUE THREAD

**Issue by DFritzsche** [bisdn/rofl-common#6]
in `cofgroupmod.cc`

`cofgroupmod::set_type(uint8_t type)`
sould be renamed to
`cofgroupmod::set_group_type(uint8_t type)`
and
`cofgroupmod::get_type() const`
sould be renamed to
`cofgroupmod::get_group_type() const`

to be consistent with e.g. 
`cofmsg_group_mod::get_group_type()`

**Comment by msune** [comment]
Disagree. set_group_type is redundant. `cofgroupmod` already indicates is the type of the group. We have to avoid long names.

**Comment by DFritzsche** [comment]
Then let's do it the other way around:  change the `cofmsg_group_mod::get_group_type()` into something like `cofmsg_group_mod::get_type()` as this also indicates it is a group.

**Comment by akoepsel** [comment]
changes implemented and merged
