### ISSUE TITLE
get_group_mod()

### ISSUE THREAD

**Issue by DFritzsche** [bisdn/rofl-common#7]
Can we please have a get_group_mod() function, similar to get_flowmod().
That is used quite often in my controller.

Example:
rofl::openflow::cofmsg_flow_mod& msg
rofl::openflow::cofflowmod fm_new = msg.get_flowmod();

and btw, get_flowmod/set_flowmod should be renamed to get_flow_mod/set_flow_mod to be consistent

**Comment by akoepsel** [comment]
changes implemented and merged
