### ISSUE TITLE
Running programs with -d x

### ISSUE THREAD

**Issue by DFritzsche** [bisdn/rofl-common#8]
Scenario: xdpd connected with a rofl-based controller, everything works fine when I run both without `-d` or with the same like `-d 5`

Issue: when it differs (e.g. `./xdpd -d 8` and `./rofl-controller -d 5`) the connection is terminated and the controller throws

`[rofl-common][crofdpt] transaction expired, xid:
<transaction xid:a601d418 msg-type:18 msg-subtype:12 >
  <expires: >
    <cclock sec:aa7c4ae6 nsec:2ad03466 >`

**Comment by DFritzsche** [comment]
tested it again xdpd with -d 8 and controller without -d

when I put the xdpd output to a file (like >& ./file.txt) it works fine, when the output goes to the console then xdpd disconnects from controller ...

**Comment by msune** [comment]
this is a timing issue; likely, -d8 is so verbose in the OF endpoint, that printing all the stats req/reply etc... to the screen takes too much that periodic HELLOs are timing out.

Does it happen with -d7?

**Comment by DFritzsche** [comment]
only -d 8 and higher

**Comment by msune** [comment]
@dfritzsche I think PR #12 would also help, since there is no need to exchange features req rep(and dumpt it to the screen) to consider the connection fully stablished.

**Comment by toanju** [comment]
feature req. rep. is absolutely mandatory, since only there the auxid to identify the connections is exchanged
